CREATE TABLE IF NOT EXISTS TYPE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DATA (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento INTEGER NOT NULL DEFAULT 2,
    obj TEXT NOT NULL,
    quando TEXT,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    creato TEXT,

    FOREIGN KEY (evento) REFERENCES TYPE(id)
);

INSERT OR IGNORE INTO TYPE (tipo) VALUES ('B-Day');
INSERT OR IGNORE INTO TYPE (tipo) VALUES ('appointment');
INSERT OR IGNORE INTO TYPE (tipo) VALUES ('remind');