

CREATE TABLE IF NOT EXISTS TYPE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DATA (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo INTEGER NOT NULL,
    obj TEXT NOT NULL,
    quando TEXT,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    creato TEXT,

    FOREIGN KEY (tipo) REFERENCES TYPE(id)
);

